{
  "name": "{{ var "name" ?: "Templated Manual Judgement" }}",
  "failPipeline": true,
  "instructions": "{{ var "instructions" ?: "Continue with Pipeline?" }}",
  "judgmentInputs": {{ var "judgmentInputs" ?: [
    {
      "value": "Oh Yeah"
    },
    {
      "value": "Nah"
    }
  ] }},
  "refId": "102",
  "requisiteStageRefIds": {{ var "requisiteStageRefIds" ?: [] }},
  "notifications": [],
  "type": "manualJudgment"
}
